export * from "./core.js";
export * from "./people.js";
export * from "./scheduling.js";
export * from "./billing.js";
export * from "./audit.js";
export * from "./curriculum.js";
export * from "./office.js";
export * from "./instructor.js";
export * from "./finance.js";
