/// <reference types="node" />
/**
 * M0 definition of done: verbatim UI strings from Anhang A/B must exist somewhere in src/domain/**.
 */
import { describe, expect, it } from "vitest";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve } from "node:path";

function readAll(dir: string): string {
  let out = "";
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) out += readAll(p);
    else if (/\.tsx?$/.test(f)) out += readFileSync(p, "utf8") + "\n";
  }
  return out;
}

const SRC = readAll(resolve(process.cwd(), "src/domain")) + readAll(resolve(process.cwd(), "src/lib"));

const STRINGS = [
  // Anhang B – rules
  "Trigger ausgelöst, nicht geraten",
  "Top-down geprüft (W → 3D → D → 4H → 1H)",
  "S&P-500-Kontext geprüft",
  "Stop deutlich vor der Liquidation",
  "Hebel im Rahmen (Scalp 4x, Makro höchstens 5x)",
  // Anhang B – setups
  "Früher Makro-Trendbruch",
  "Philosophie 1: Diagonale Downtrend-Linie und RSI-Trendlinie brechen. Höchstes Risiko, bester Preis.",
  "Diagonale Downtrend-Linie gebrochen",
  "Lower-High-Bruch 82.829",
  "Philosophie 2: Weekly Close über 82.829 UND Weekly RSI über 62,09. Beides nötig.",
  "4-Jahres-Zyklus-Bestätigung",
  "Philosophie 3: Kein Zyklus-Bottom bis 21. Nov. Spätester Einstieg, höchste Bestätigung, schlechtester Preis.",
  "Wochenschlüsse durchgehend über 82.829",
  "Makro-Long Support-Zone",
  "Preis bei 81.500–82.200 plus Falling-Knife-Filter. Long-% allein ist kein Kaufsignal.",
  "Preis in Support-/Liquiditätszone (BSL/EQL)",
  "Whale-vs-Retail-Delta positiv, 2–3 Kerzen in Folge",
  "RSI: bullische Divergenz oder Trendlinienbruch",
  "Leg-Up-Ladder",
  "Bestätigtes Measured-Move-Ziel mit Struktur nach oben durchbrochen: 15–25 % des verbleibenden Makro-Cash zukaufen.",
  "Add höchstens 25 % des verbleibenden Makro-Cash",
  "4H-Breakout über 85.900",
  "4H-Schluss über 85.900: Ziel 87.200, dann 89.000–90.000. Invalidierung zurück unter 85.300.",
  "S&P nicht in Ablehnung an 7.834–7.840",
  "4H-Neckline-Short unter 84.500",
  "4H-Schluss unter 84.500: Ziel 82.000–81.500, Stop über 85.300.",
  "Breakout-Ablehnung 85.700–85.900",
  "Preis scheitert an der Ausbruchszone: Rückfall-Risiko bis zum BOS-Test bei 82.000.",
  "BSL/EQL Liquidity Sweep",
  "Preis fegt eine Liquiditätszone ab, bevor der eigentliche Move kommt.",
  "Reclaim, Struktur dreht",
  "RSI-Trendlinienbruch",
  "Diagonale RSI-Trendlinie bricht: Momentum-Signal. Keine horizontalen RSI-Level.",
  "Struktur bestätigt (BOS/CHoCH)",
  "Backtest-Signal (214er)",
  "Eigene Strategie: 62,15 % Winrate im Backtest. 4x Hebel, 250 USDT Margin isoliert, etwa 2 Trades pro Monat.",
  "Trailing-Stop ab +8–10 % geplant",
  "214 Signale",
  "BINANCE:BTCUSDT",
  "topTraderAccountsLongShort",
  "whaleRetailDelta",
  "binance_perp_stable",
  "https://hyblockcapital.com/console?user=HBC&dashboard=default&shared=true",
  // Anhang B.3 constants
  '"Ruhig", "Fokussiert", "Unsicher", "FOMO", "Gierig", "Revenge"',
  '"Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"',
  '"Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"',
  "Gesamt",
  "Schwach",
  "Gering",
  "Mittel",
  "Break-even",
  // Anhang A – explainers
  "Noch keine abgeschlossenen Trades. Der Wert füllt sich mit deinem ersten Trade.",
  "Summe aller realisierten Gewinne und Verluste deiner abgeschlossenen Trades, nach Gebühren. Offene Positionen zählen erst mit dem Schließen.",
  "Rendite aufs Startkapital",
  "Kontostand jetzt",
  "Bester Trade",
  "Schlechtester Trade",
  "Gezahlte Gebühren",
  "Offene Positionen",
  "Achtung: mehr als die Hälfte des Gewinns stammt aus einem einzigen Trade.",
  "Der Gewinn verteilt sich auf mehrere Trades.",
  "Im Minus. Schau in die Checklisten-Auswertung, welche Regeln bei den Verlusten gefehlt haben.",
  "Mit Checkliste komplett",
  "Win-Rate und Erwartung schwanken bis etwa 30 Trades stark.",
  "Genug Trades für belastbare Kennzahlen.",
  "Break-even = Ø Verlust ÷ (Ø Gewinn + Ø Verlust)",
  "Backtest-Referenz",
  "Chance-Risiko real (Ø Gewinn ÷ Ø Verlust)",
  "Nötige Win-Rate",
  "Für die Break-even-Rechnung brauchst du mindestens einen Gewinner und einen Verlierer.",
  "Prozentpunkte über deiner Break-even-Win-Rate. Das System ist profitabel.",
  "Prozentpunkte unter deiner Break-even-Win-Rate. Entweder öfter richtig liegen oder Gewinner länger laufen lassen.",
  "Profit-Faktor",
  "Bruttogewinne",
  "Bruttoverluste",
  "Noch kein Verlust. Der Faktor wird aussagekräftig, sobald Verluste dabei sind.",
  "Unter 1: Die Verluste sind größer als die Gewinne.",
  "Zwischen 1 und 1,5: profitabel, aber knapp. Gebühren und Funding können das kippen.",
  "Zwischen 1,5 und 2: solides System.",
  "Über 2: starkes Verhältnis von Gewinnen zu Verlusten.",
  "Ø R-Multiple",
  "R = P&L ÷ (|Einstieg − Stop| × Menge) · Ø über",
  "Trades mit Stop",
  "Bester R",
  "Schlechtester R",
  "Trades mit ≥ 2 R",
  "Trag bei deinen Trades einen Stop-Loss ein, dann berechne ich das R-Multiple.",
  "Das heißt, ein Stop wurde verschoben oder nicht eingehalten.",
  "Positiver Durchschnitt: Im Schnitt holst du mehr als du riskierst.",
  "Negativer Durchschnitt: Im Schnitt verlierst du einen Teil deines Risikos pro Trade.",
  "Maximaler Drawdown",
  "Höchststand",
  "Aktueller Abstand zum Hoch",
  "Hoch bei",
  "Tief bei",
  "Unter 5 %: sehr kontrolliertes Risiko.",
  "Zwischen 5 und 15 %: vertretbar, aber im Blick behalten.",
  "Über 15 %: Positionsgrößen oder Hebel prüfen (Regel: Scalp 4x, Makro höchstens 5x).",
  "Erwartungswert",
  "Pro Trade in Kursbewegung",
  "Positiv: Mit jedem weiteren Trade nach diesem Muster wächst das Konto im Schnitt.",
  "Negativ: Im Schnitt kostet dich jeder Trade Geld.",
  "Hochrechnung aufs Jahr",
  "Startkapital",
  "Ø pro Monat",
  "Konto in 12 Monaten",
  "Wenig Daten: Die Hochrechnung wird ab etwa 30 Tagen und 10 Trades belastbar.",
  "Die Zahl beschreibt deine bisherige Performance, sie ist keine Prognose.",
  "> +9.900 %",
  "Serie",
  "3 Verluste in Folge. Pause machen und die Checkliste der letzten Trades prüfen.",
  "Kein Warnsignal.",
  // A.10 backtest
  "Anteil gewonnener Trades, verglichen mit den 214 Backtest-Signalen.",
  "Durchschnittliche Kursbewegung vom Einstieg zum Ausstieg bei gewonnenen Trades, ohne Hebel. So ist auch der Backtest gerechnet.",
  "Durchschnittliche Kursbewegung bei verlorenen Trades, ohne Hebel. Ein kleinerer Wert als im Backtest heißt: du schneidest Verluste früher ab.",
  "Durchschnittliche Kursbewegung über alle Trades. Das ist die Zahl, an der sich Über- oder Unterperformance entscheidet.",
  "Datenbasis",
  "Noch keine Trades mit Ein- und Ausstieg.",
  "Besser als der Backtest.",
  "Schlechter als der Backtest.",
  "Du überperformst den Backtest",
  "Du liegst unter dem Backtest",
  "Noch kein Vergleich möglich",
  "ab 30 Trades belastbar",
  "Gewinner, Verlierer und Erwartung als Kursbewegung vom Einstieg zum Ausstieg, ohne Hebel, wie im Backtest.",
  "Grundlage „Backtest-Signal (214er)“ wurde gelöscht – Vergleich nur über alle Trades.",
  // A.11 setup detail
  "Keine Regeln hinterlegt.",
  "Ø Gewinn / Ø Verlust",
  "Checkliste komplett",
  "Ø Kursbewegung",
  "Ab etwa 10 Trades lässt sich die Grundlage fair bewerten.",
  "Diese Grundlage verdient Geld. Weiter so, gleiche Regeln.",
  "Diese Grundlage kostet Geld. Regeln schärfen oder seltener handeln.",
  "Noch keine abgeschlossenen Trades mit dieser Grundlage.",
  // A.12 checklist
  "Checklisten-Auswertung",
  "Vergleicht Trades, bei denen du alle Punkte (Grundregeln plus Punkte der gewählten Grundlagen) abgehakt hast",
  "Trades mit Checkliste",
  "Alles erfüllt",
  "Mit Lücken",
  "Differenz",
  "Für einen Vergleich brauchst du Trades mit und ohne vollständige Checkliste.",
  "Mit voller Checkliste gewinnst du öfter. Die Regeln wirken.",
  "Mit Lücken läuft es bisher besser. Prüfe, ob die Checklisten-Punkte zu deinem Stil passen.",
  "Am häufigsten ausgelassen",
  "Bisher alles abgehakt.",
  // A.13 falling knife
  "Ein steigender Top-Trader-Long-% allein ist kein Kaufsignal: Top-Trader akkumulieren oft gestaffelt, während der Preis noch fällt. Ein Makro-Long ist nur valide, wenn alle 4 Punkte erfüllt sind.",
  "Preis in Support-/Liquiditätszone",
  "Erster Higher Low oder BOS auf 1H/4H",
  "Whale-vs-Retail-Delta positiv, 2–3 Kerzen",
  "RSI bullische Divergenz oder Trendlinienbruch",
  "wartet auf Live-Kurs",
  "deine Ablesung",
  "✓ erfüllt",
  "✕ offen",
  "Alle 4 Punkte erfüllt: Makro-Long-Trigger ist valide (T3 prüfen).",
  "Anti-Muster: Long-% steigt, aber Delta ist nicht positiv und die Struktur dreht nicht. Messer fangen: beobachten statt handeln.",
  "von 4 erfüllt. Kein Kaufsignal, weiter beobachten.",
  "Makro-Long-Trigger valide.",
  "Anti-Muster: Messer fangen. Beobachten.",
  "Kein Kaufsignal. Tippen für Details.",
  "Live von Hyblock",
  // Plan 4.9 trigger
  "Volles Bär-Szenario",
  "Long-Trigger aktiv",
  "Short-Trigger aktiv",
  "Range, kein Trigger",
  "Ziel 66.000–70.000.",
  "Ziel 87.200, dann 89.000–90.000. Invalidierung unter",
  "Ziel 82.000–81.500, Stop über",
  "Abwarten.",
  "Neues Szenario: ",
  "Falling-Knife-Filter prüfen, bevor du kaufst.",
  "Long-Trigger in Reichweite",
  "Long-Invalidierung",
  // Patterns / ranking / CSV
  "Muster in deinen Trades",
  "Plan befolgt oder nicht, Long gegen Short, Überzeugung, Gefühl und Wochentag. Das füllt sich mit deinen Trades.",
  "Plan befolgt?",
  "Richtung",
  "Überzeugung",
  "Gefühl beim Einstieg",
  "Wochentag",
  "bestes / schlechtestes",
  "bester / schlechtester",
  "Hoch (4–5)",
  "Niedrig (1–3)",
  "Noch keine Trades zugeordnet. Sobald du Trades mit Grundlage einträgst, erscheint hier das Ranking.",
  "Kursbewegung %",
  "Plan befolgt",
  "Begründung",
];

describe("verbatim UI strings in src/domain", () => {
  it("has at least 60 strings listed", () => {
    expect(STRINGS.length).toBeGreaterThanOrEqual(60);
  });
  it.each(STRINGS)("contains %s", (str) => {
    expect(SRC.includes(str)).toBe(true);
  });
});
